### ISSUE TITLE
Feat: Special, single-use move to wipe out the visible enemies

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#115]
I think I want to resurrect this idea:

> Or, player could use a special key combo. which can only be used once in a single play (like Z-moves, if you know pokemon...), and it will cause all the enemies/trashes on the screen to be killed, yielding very large number of points at once. This could be used when the player sees a large number of trashes on-screen...

Sounds like something possible!

_Originally posted by @DiddiLeija in https://github.com/DiddiLeija/diddi-and-the-bugs/issues/13#issuecomment-1483701365_

**Comment by DiddiLeija** [comment]
@HarshNarayanJha, here it is. Feel free to link this issue to any PR you make :)

**Comment by HarshNarayanJha** [comment]
Done! See #116

**Comment by DiddiLeija** [comment]
Ok! #116 is merged. Now I'll take the graphics/sound/docs part ;)

**Comment by DiddiLeija** [comment]
All done! Thanks @HarshNarayanJha for the initial work.
Feel free to drop your feedback or suggestions about this change!
