### ISSUE TITLE
Major feat: Add-on support

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#137]
**Is your feature request related to a problem? Please describe.**

Though resource modifications have always been "implicitly" supported [^1], it's never been a documented/encouraged feature. But it turns out that such modifications could customize each user's experience in a unique way.

**Describe the solution you'd like**

Add-on support. I mean, a way to support a secondary resource file that "superseeds" the main one. Of course, this will need a major refactor in our API to accept this "external source", but it's still possible.

A few other related ideas (that may come once we get the above things done):

- Support modifying the background color (which, by now, will always be black)
- Add the star appearance to the resource file, so these can also be customized.
- Distribute a sort of "official DLC bundle" for free to get y'all started! :smiley:

**Describe alternatives you've considered**

Just document the possibility of changing the main `resource.pyxres` file [^1]?

**Additional context**

Feel free to provide feedback or your thoughts on this feature!

And thanks to @HarshNarayanJha for providing the initial idea (via our Discord server), that is highly appreciated!

[^1]: You always had the possibility to modify `resource.pyxres`, which contains the main image sources, the original music, etc.

**Comment by HarshNarayanJha** [comment]
I have a few suggestions for the implementation. We could add an option to the main menu to “select” the skin pack, just by listing all the `resource.pyxres` files and loading the selected one. And whether pyxel supports dynamic loading of resources, we could change the skin of things on the main menu also, while the layer selects, to let them see the skin pack.

@DiddiLeija checkout some other info on discord

**Comment by DiddiLeija** [comment]
Ok! Sounds like the best way to implement the feat, though that will require a heavier implementation (that's why I've added this to the 4.x milestone), but it's a pretty nice idea :)

**Comment by HarshNarayanJha** [comment]
Opened PR #138

**Comment by DiddiLeija** [comment]
A follow-up PR is live at #140.
