### ISSUE TITLE
Fire Bug

### ISSUE THREAD

**Issue by HarshNarayanJha** [DiddiLeija/diddi-and-the-bugs#18]
There is an graphical issue in bullet firing, where if you keep the space button held for more than two consecutive frames, then a long continuous row of bullets will appear onscreen, which doesn't causes any damage to enemies...

To fix this, I will soon open a PR
![fire_bug](https://user-images.githubusercontent.com/50262541/148880319-db6da80a-aae1-41c3-bd2a-3cc4bf8adef7.png)

**Comment by HarshNarayanJha** [comment]
Fixed, here's the PR: #19

**Comment by DiddiLeija** [comment]
Hmm... I'm wondering if this **should** be a bug, or just a "hard-to-find trick".

**Comment by DiddiLeija** [comment]
Well... I never tried to keep the space key pressed. Let's consider this a glitch, and fix it. Thanks for reporting @HarshNarayanJha!

**Comment by HarshNarayanJha** [comment]
> Hmm... I'm wondering if this **should** be a bug, or just a "hard-to-find trick".

But those continuous bullets don't hit.

**Comment by DiddiLeija** [comment]
They hit on my case :man_shrugging:.

**Comment by DiddiLeija** [comment]
Hmm... maybe it works in the new Pyxel (`1.6.1`). If you ran using `1.5.8` (like in #20), the restart logics are broken and the fire bug is now functional?

Can you run `pip install -U pyxel` and recreate the behavior?

**Comment by HarshNarayanJha** [comment]
Oh yes, updated to Pyxel(`1.6.1`). Two things happened:
1. The bug's gone! Those continuous bullets are now killing enemies!
2. Restart Bugs #20 is confirmed.

So, disallowing is usage of continuous bullets (as I did before), is not a good idea. We should allow that "hard-to-find trick" (one easter egg done! congrats!). But I don't like the visual style of it....
Isn't this one nice?
![image](https://user-images.githubusercontent.com/50262541/149254166-ce993561-a09e-4fab-83b1-31f261b36a4b.png)
(Already confirmed, they do hit!)

**Comment by DiddiLeija** [comment]
> We should allow that "hard-to-find trick" (one easter egg done! congrats!)

:wink:

> Isn't this one nice?

Yeah, it looks better. Thanks for the fix!
