### ISSUE TITLE
Overlapping Enemies

### ISSUE THREAD

**Issue by HarshNarayanJha** [DiddiLeija/diddi-and-the-bugs#21]
The issue is that whenever new enemies or trash is activated, chances are there that they may be overlapping, or partially overlapping. And due to varying speeds, they may overlap somewhere in-between.
![overlapping_bug](https://user-images.githubusercontent.com/50262541/149554788-8437f9c5-1a28-4c5d-a218-24c7bc22c06d.png)

**Comment by DiddiLeija** [comment]
This was an intentional behavior, as far as I remember. The "continous fire trick" may help here, right?

**Comment by HarshNarayanJha** [comment]
Oh! Yes, Really, then it's fine. 
Closing.
