### ISSUE TITLE
Add a "notifications bar" for messages

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#29]
We can also make the game more interactive by giving a notification to the player from Diddi (who modified the spaceship, as in your story), that the player has unlocked a secret function of the ship....

_Originally posted by @HarshNarayanJha in https://github.com/DiddiLeija/diddi-and-the-bugs/issues/13#issuecomment-1019032635_

---

If we want to do this, it will be after cutting a release to save our latest modifications.

**Comment by DiddiLeija** [comment]
I already have an idea to do this. I'll post a PR soon. By now, I self-assign this issue.

**Comment by DiddiLeija** [comment]
Uh, well... this is what I have now:

![pyxel-20220131-134341](https://user-images.githubusercontent.com/83621221/151861725-6dca7355-481b-431f-a1b8-3ee705771a69.png)

There's a bar below the game. It is still present when you loose, win, pause or restart. Now I have to move the messages part.

**Comment by DiddiLeija** [comment]
Here are a few messages:

![pyxel-20220201-113853](https://user-images.githubusercontent.com/83621221/152021062-3f18a600-e4d4-4166-a0a7-82e4c73aace0.png)

![pyxel-20220201-113953](https://user-images.githubusercontent.com/83621221/152021116-e7acdbd8-de91-432c-84a9-2913f7afb22e.png)

![pyxel-20220201-114022](https://user-images.githubusercontent.com/83621221/152021357-e73a6112-d47b-47ba-a114-492af36afed4.png)

And some others. I currently have these messages:

- Game start (initialization)
- Pause / Resume
- Restart
- Continous bullets
- Win / Loose

Should we notify something else?

**Comment by HarshNarayanJha** [comment]
Great... Is this system stable now?, if it is push the changes then we will think about other notifications and/or message improvements.

**Comment by DiddiLeija** [comment]
I actually added some secret messages (available via an undocumented `M` key) at #38. You can add messages to it, or generate messages on other events.
