### ISSUE TITLE
We have a Discord server!

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#45]
I recently opened a Discord server, to create a small "community" around Diddi And The Bugs. I expect this server to feed many future projects, so you can talk about this game at the `#diddi-and-the-bugs` channel. You can share tips, scores, and some related stuff.

If you want to join, click here: https://discord.gg/DfrHxT9ENy [^1]

[^1]: The old link (`https://discord.gg/5XDWbyd5`) is now broken, so we made a new one :)

**Comment by DiddiLeija** [comment]
cc @HarshNarayanJha (if you're interested in joining!)

**Comment by HarshNarayanJha** [comment]
already joined!

**Comment by DiddiLeija** [comment]
It seems like the Discord invite became invalid, so I'll have to add a new one :/

**Comment by DiddiLeija** [comment]
I made a new one, and edited the first post :)

**Comment by DiddiLeija** [comment]
Closing & locking this, since there's nothing to comment by now :)
