### ISSUE TITLE
Add a title menu

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#59]
**Is your feature request related to a problem? Please describe.**

At our Discord server [^1], we were discussing about having an introduction menu, instead of starting the game directly. It would be nice because starting inmediately is... a bit weird :upside_down_face:

**Describe the solution you'd like**

A title menu for the 3.x series. Since we want to merge this in a 3.x version, this will fit with #52, btw.

**Describe alternatives you've considered**

Keeping as-is.

**Additional context**

N/A

[^1]: See #45.

**Comment by DiddiLeija** [comment]
cc @HarshNarayanJha

**Comment by HarshNarayanJha** [comment]
I think of the title screen like
> - The Game title slowly fades in of the black, then,
> - The game **plays** in the background (i.e. automatically, ether pre-rendered or actually, if you have seen the title screen of LoZ: OOT)
> - Then upon pressing a key, screen fades out into the real gameplay!

**Comment by DiddiLeija** [comment]
That sounds like a pretty nice idea! I think we gotta try it!

**Comment by DiddiLeija** [comment]
Ok, I have a PR in progress, see #60.
