### ISSUE TITLE
Post-jam goals

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#7]
**Hi visitors!**

This project was made for the [GameOff 2021](https://itch.io/jam/game-off-2021) event. However, the end of that jam (in 2 days) won't mean the death of this project! :smiley: Those who rated this game and commented [here](https://itch.io/jam/game-off-2021/rate/1293582) and [here](https://itch.io/jam/game-off-2021/topic/1833717/challenge-try-my-game-then-tell-me-your-points) gave useful feedback. Thanks in advance to those who took the risk to try this game! :heart:

I found some important issues/improvements (starting with the creepy music! :confused:) basing on those comments. Also, since I'm the owner and played lots of times, I noticed more improvements by myself.

To keep everything in the same place, I made a project board to track the goals we want to cover after the jam ends: https://github.com/DiddiLeija/diddi-and-the-bugs/projects/1

Feel free to comment here if you want more improvements soon :wink:

**Comment by DiddiLeija** [comment]
@HarshNarayanJha, I think these goals can help you if you want to contribute after the jam :) Also, if you wanna add other goals, feel free to tell me here!

**Comment by HarshNarayanJha** [comment]
Sure, ready to help.

**Comment by DiddiLeija** [comment]
Ok. I'll cut a 1.0.0 (see #8). After that, contributions will be fully open :)

**Comment by DiddiLeija** [comment]
> Ok. I'll cut a 1.0.0 (see #8) release. After that, contributions will be fully open :)

I released a [1.0.0 release](https://diddileija.itch.io/diddi-and-the-bugs/devlog/331510/version-100) a few minutes ago. Feel free to send your contributions!

**Comment by DiddiLeija** [comment]
Closing this, since we already cutter post-jam releases. I will close https://github.com/DiddiLeija/diddi-and-the-bugs/projects/1 soon, too.
